#!/bin/bash

# See 
# http://www.imagemagick.org/Usage/compare/#difference
# todo : automaticall crop out 

#mkdir -p test_images
#wget https://userweb.jlab.org/~whit/hallc/spring17_angle_snaps/SHMS_angle_03604.jpg -O test_images/angle_test1.jpg
#wget https://userweb.jlab.org/~whit/hallc/spring17_angle_snaps/SHMS_angle_03605.jpg -O test_images/angle_test2.jpg
#wget https://userweb.jlab.org/~whit/hallc/spring17_angle_snaps/SHMS_angle_03606.jpg -O test_images/angle_test3.jpg
#wget https://userweb.jlab.org/~whit/hallc/spring17_angle_snaps/SHMS_angle_03131.jpg  -O test_images/angle_test4.jpg

mkdir -p test_results

# produces detailed difference
composite \
  test_images/angle_test1.jpg \
  test_images/angle_test2.jpg \
  -compose difference  test_results/difference_1_2.png

composite \
  test_images/angle_test1_offset.jpg \
  test_images/angle_test2.jpg \
  -compose difference  test_results/difference_1_offset_2.png

composite \
  test_images/angle_test2.jpg \
  test_images/angle_test3.jpg \
  -compose difference  test_results/difference_2_3.png

composite \
  test_images/angle_test2.jpg \
  test_images/angle_test4.jpg \
  -compose difference  test_results/difference_2_4.png

convert \
  test_images/angle_test1_offset.jpg \
  test_images/angle_test2.jpg \
  -compose difference -composite \
  -threshold 0 -separate -evaluate-sequence Add \
  test_results/compose_diff_threshold.png

compare -metric FUZZ -fuzz 5% \
  test_images/angle_test1.jpg \
  test_images/angle_test2.jpg \
          -compose Src -highlight-color White -lowlight-color Black \
  test_results/compare_1_2_fuzz_5.png
echo " "
echo " the number above is for two runs with the same angle "
echo " "


compare -metric FUZZ -fuzz 10% \
  test_images/angle_test1.jpg \
  test_images/angle_test2.jpg \
          -compose Src -highlight-color White -lowlight-color Black \
  test_results/compare_1_2_fuzz_10.png
echo " "
echo " the number above is for two runs with the same angle "
echo " "

compare -metric FUZZ -fuzz 15% \
  test_images/angle_test1.jpg \
  test_images/angle_test2.jpg \
          -compose Src -highlight-color White -lowlight-color Black \
  test_results/compare_1_2_fuzz_15.png
echo " "
echo " the number above is for two runs with the same angle "
echo " "
# metric FUZZ is a crude quantization

compare -metric FUZZ -fuzz 15% \
  test_images/angle_test1_offset.jpg \
  test_images/angle_test2.jpg \
          -compose Src -highlight-color White -lowlight-color Black \
  test_results/compare_1_offset_2_fuzz_15.png
echo " "
echo "FUZZ the difference with the same angle but one offset"
echo " "

compare -metric AE -fuzz 15% \
  test_images/angle_test1_offset.jpg \
  test_images/angle_test2.jpg \
          -compose Src -highlight-color White -lowlight-color Black \
  test_results/compare_1_offset_2_fuzz_15.png
echo " "
echo "AE the difference with the same angle but one offset"
echo " "

compare -metric AE -fuzz 15% \
  test_images/angle_test1.jpg \
  test_images/angle_test2.jpg \
          -compose Src -highlight-color White -lowlight-color Black \
  test_results/compare_1_offset_2_fuzz_15.png
echo " "
echo "AE the difference with the same angle but one offset"
echo " "


compare -metric PAE -fuzz 15% \
  test_images/angle_test1_offset.jpg \
  test_images/angle_test2.jpg \
          -compose Src -highlight-color White -lowlight-color Black \
  test_results/compare_1_offset_2_fuzz_15.png
echo " "
echo "PAE the difference with the same angle but one offset"
echo " "

mse1=$(compare -metric MSE -fuzz 15% \
  test_images/angle_test1_offset.jpg \
  test_images/angle_test2.jpg \
          -compose Src -highlight-color White -lowlight-color Black \
          test_results/compare_1_offset_2_fuzz_15.png 2>&1 )
echo " "
echo " $mse1"
echo "MSE the difference with the same angle but one offset"
echo " "

mse2=$(compare -metric MSE -fuzz 15% \
  test_images/angle_test1.jpg \
  test_images/angle_test2.jpg \
          -compose Src -highlight-color White -lowlight-color Black \
          test_results/compare_1_offset_2_fuzz_15.png 2>&1 )
echo " "
echo " $mse2"
echo "MSE the difference with the same angle but one offset"
echo " "
mse2array=($mse2)
echo "${mse2array[0]}"

# chop off the bottom part of the image with the timestamp
convert  test_results/difference_2_4.png -background black -gravity south -chop x40 \
  test_results/difference_2_4_chopped.png

convert  test_results/compare_1_offset_2_fuzz_15.png -background black -gravity south -chop x40 \
  test_results/compare_1_offset_2_fuzz_15_chopped.png

#convert test_results/compare_1_offset_2_fuzz_15_chopped.png -precision 15 -format %[fx:int(mean*w*h+0.5)] info:

#j
#jconvert test_results/compare_1_offset_2_fuzz_15_chopped.png  -format %[fx:int(mean*w*h+0.5)] info:
#jidentify test_results/compare_1_offset_2_fuzz_15_chopped.png  -format %[fx:int(mean*w*h+0.5)] info:



#-precision 15 -format %[fx:int(mean*w*h+0.5)] info:
